# See https://ezcv.readthedocs.io for documentation
name: Michael Wu
theme: dimension
resume: false
biography: 4th Student at the University of Technology Sydney studying the Bachelor of Science in Games Development. I have experience with C# with .NET and the Unity Game Engine, as well as C++ with the Unreal Engine. I'm actually just writing more things here so that the entire space is filled with stuff.
email: w.michael.u@gmail.com
role: IT Operations Intern
company: University of Technology Sydney
social:
  github: WichaelMu
  linkedin: michael-wu-3842b512b