name: MW-EZCV Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name:  Checkout MW-EZCV
      uses: actions/checkout@v2
      with:
        repository: WichaelMu/MW-EZCV
        path: 'MW-EZCV'

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Build MW-EZCV
      run: |
        python ./MW-EZCV/setup.py install

    - name: List
      run: ls -R
        
    - name: Build HTML Files from MW-EZCV
      run: |
        python ./MW-EZCV/ezcv/cli.py build

    - name: Deploy Docs
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: site
